// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/accesos/roles" | "/accesos/usuarios" | "/activos" | "/activos/[id]" | "/activos/[id]/editar" | "/activos/nuevo" | "/alertas" | "/checklist" | "/combustible" | "/configuracion" | "/contacto" | "/dashboard" | "/flotas" | "/flotas/[id]" | "/flotas/[id]/editar" | "/flotas/nuevo" | "/forgot-password" | "/generadores" | "/geolocalizacion" | "/gestion/sedes" | "/gestion/seguros" | "/gestion/tipos-aceite" | "/login" | "/mantenimiento" | "/mantenimiento/[id]/editar" | "/mantenimiento/aceites" | "/mantenimiento/cambios-aceite" | "/mantenimiento/inventario" | "/mantenimiento/kilometraje" | "/mantenimiento/nuevo" | "/mantenimiento/registro-combustible" | "/motores" | "/motores/[id]" | "/motores/[id]/editar" | "/motores/historial" | "/motores/mantenimientos" | "/motores/nuevo" | "/operaciones" | "/operaciones/asignaciones" | "/operaciones/conductores" | "/operaciones/conductores/[id]/editar" | "/operaciones/conductores/nuevo" | "/perfil" | "/reportes" | "/reportes/[slug]" | "/solicitar-demo" | "/superadmin" | "/superadmin/auditoria" | "/superadmin/clientes" | "/superadmin/configuracion" | "/superadmin/contenido" | "/superadmin/crm" | "/superadmin/empresas" | "/superadmin/facturacion" | "/superadmin/leads" | "/superadmin/login" | "/superadmin/modulos" | "/superadmin/planes" | "/superadmin/usuarios"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/accesos/roles": {}
  "/accesos/usuarios": {}
  "/activos": {}
  "/activos/[id]": { "id": string; }
  "/activos/[id]/editar": { "id": string; }
  "/activos/nuevo": {}
  "/alertas": {}
  "/checklist": {}
  "/combustible": {}
  "/configuracion": {}
  "/contacto": {}
  "/dashboard": {}
  "/flotas": {}
  "/flotas/[id]": { "id": string; }
  "/flotas/[id]/editar": { "id": string; }
  "/flotas/nuevo": {}
  "/forgot-password": {}
  "/generadores": {}
  "/geolocalizacion": {}
  "/gestion/sedes": {}
  "/gestion/seguros": {}
  "/gestion/tipos-aceite": {}
  "/login": {}
  "/mantenimiento": {}
  "/mantenimiento/[id]/editar": { "id": string; }
  "/mantenimiento/aceites": {}
  "/mantenimiento/cambios-aceite": {}
  "/mantenimiento/inventario": {}
  "/mantenimiento/kilometraje": {}
  "/mantenimiento/nuevo": {}
  "/mantenimiento/registro-combustible": {}
  "/motores": {}
  "/motores/[id]": { "id": string; }
  "/motores/[id]/editar": { "id": string; }
  "/motores/historial": {}
  "/motores/mantenimientos": {}
  "/motores/nuevo": {}
  "/operaciones": {}
  "/operaciones/asignaciones": {}
  "/operaciones/conductores": {}
  "/operaciones/conductores/[id]/editar": { "id": string; }
  "/operaciones/conductores/nuevo": {}
  "/perfil": {}
  "/reportes": {}
  "/reportes/[slug]": { "slug": string; }
  "/solicitar-demo": {}
  "/superadmin": {}
  "/superadmin/auditoria": {}
  "/superadmin/clientes": {}
  "/superadmin/configuracion": {}
  "/superadmin/contenido": {}
  "/superadmin/crm": {}
  "/superadmin/empresas": {}
  "/superadmin/facturacion": {}
  "/superadmin/leads": {}
  "/superadmin/login": {}
  "/superadmin/modulos": {}
  "/superadmin/planes": {}
  "/superadmin/usuarios": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
