// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/accesos/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accesos/roles">> = Specific
  const handler = {} as typeof import("../../src/app/accesos/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accesos/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accesos/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/accesos/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/activos/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activos/[id]/editar">> = Specific
  const handler = {} as typeof import("../../src/app/activos/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/activos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activos/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/activos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/activos/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activos/nuevo">> = Specific
  const handler = {} as typeof import("../../src/app/activos/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/activos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activos">> = Specific
  const handler = {} as typeof import("../../src/app/activos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alertas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alertas">> = Specific
  const handler = {} as typeof import("../../src/app/alertas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checklist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checklist">> = Specific
  const handler = {} as typeof import("../../src/app/checklist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/combustible/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/combustible">> = Specific
  const handler = {} as typeof import("../../src/app/combustible/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../src/app/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/flotas/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flotas/[id]/editar">> = Specific
  const handler = {} as typeof import("../../src/app/flotas/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/flotas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flotas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/flotas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/flotas/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flotas/nuevo">> = Specific
  const handler = {} as typeof import("../../src/app/flotas/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/flotas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flotas">> = Specific
  const handler = {} as typeof import("../../src/app/flotas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/generadores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/generadores">> = Specific
  const handler = {} as typeof import("../../src/app/generadores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/geolocalizacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/geolocalizacion">> = Specific
  const handler = {} as typeof import("../../src/app/geolocalizacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gestion/sedes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gestion/sedes">> = Specific
  const handler = {} as typeof import("../../src/app/gestion/sedes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gestion/seguros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gestion/seguros">> = Specific
  const handler = {} as typeof import("../../src/app/gestion/seguros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gestion/tipos-aceite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gestion/tipos-aceite">> = Specific
  const handler = {} as typeof import("../../src/app/gestion/tipos-aceite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento/[id]/editar">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/aceites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento/aceites">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/aceites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/cambios-aceite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento/cambios-aceite">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/cambios-aceite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/inventario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento/inventario">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/inventario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/kilometraje/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento/kilometraje">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/kilometraje/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento/nuevo">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mantenimiento/registro-combustible/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento/registro-combustible">> = Specific
  const handler = {} as typeof import("../../src/app/mantenimiento/registro-combustible/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/motores/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/motores/[id]/editar">> = Specific
  const handler = {} as typeof import("../../src/app/motores/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/motores/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/motores/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/motores/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/motores/historial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/motores/historial">> = Specific
  const handler = {} as typeof import("../../src/app/motores/historial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/motores/mantenimientos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/motores/mantenimientos">> = Specific
  const handler = {} as typeof import("../../src/app/motores/mantenimientos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/motores/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/motores/nuevo">> = Specific
  const handler = {} as typeof import("../../src/app/motores/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/motores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/motores">> = Specific
  const handler = {} as typeof import("../../src/app/motores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operaciones/asignaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operaciones/asignaciones">> = Specific
  const handler = {} as typeof import("../../src/app/operaciones/asignaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operaciones/conductores/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operaciones/conductores/[id]/editar">> = Specific
  const handler = {} as typeof import("../../src/app/operaciones/conductores/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operaciones/conductores/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operaciones/conductores/nuevo">> = Specific
  const handler = {} as typeof import("../../src/app/operaciones/conductores/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operaciones/conductores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operaciones/conductores">> = Specific
  const handler = {} as typeof import("../../src/app/operaciones/conductores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operaciones">> = Specific
  const handler = {} as typeof import("../../src/app/operaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../src/app/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reportes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reportes/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reportes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reportes">> = Specific
  const handler = {} as typeof import("../../src/app/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solicitar-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solicitar-demo">> = Specific
  const handler = {} as typeof import("../../src/app/solicitar-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/auditoria">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/contenido/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/contenido">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/contenido/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/crm">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/empresas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/empresas">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/empresas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/facturacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/facturacion">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/facturacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/leads">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/login">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/modulos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/modulos">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/modulos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/planes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/planes">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/planes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
