import type { ReportRecord } from "@/types/fleet";

export const defaultReports = [
  {
    id: "rep-001",
    tenantId: "tenant-fleetops",
    name: "Reporte general",
    category: "Operativo",
    format: "PDF",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Vista consolidada de seguros, mantenimiento y proxima criticidad por unidad.",
  },
  {
    id: "rep-002",
    tenantId: "tenant-fleetops",
    name: "Vehiculos asignados",
    category: "Operativo",
    format: "XLSX",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Historial de asignacion entre conductores y vehiculos con estado documental.",
  },
  {
    id: "rep-003",
    tenantId: "tenant-fleetops",
    name: "Gastos realizados",
    category: "Mantenimiento",
    format: "XLSX",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Detalle de gastos operativos ligados a combustible y mantenimiento.",
  },
  {
    id: "rep-004",
    tenantId: "tenant-fleetops",
    name: "Reporte checklist",
    category: "Operativo",
    format: "PDF",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Historico de inspecciones por unidad, categoria y evidencia de campo.",
  },
  {
    id: "rep-005",
    tenantId: "tenant-fleetops",
    name: "Reporte combustible",
    category: "Combustible",
    format: "PDF",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Historico de cargas, kilometraje, costo total y estacion de servicio.",
  },
  {
    id: "rep-006",
    tenantId: "tenant-fleetops",
    name: "Alertas enviadas por conductores",
    category: "Ejecutivo",
    format: "PDF",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Alertas operativas elevadas por conductores y estado de seguimiento.",
  },
  {
    id: "rep-007",
    tenantId: "tenant-fleetops",
    name: "Reporte inventarios",
    category: "Mantenimiento",
    format: "XLSX",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Movimientos y stock remanente de inventario critico para taller.",
  },
  {
    id: "rep-008",
    tenantId: "tenant-fleetops",
    name: "Reporte generadores",
    category: "Operativo",
    format: "PDF",
    status: "Listo",
    lastGeneratedAt: "Sin generar",
    description: "Estado operativo, horas y proximos servicios para generadores electricos.",
  },
] satisfies ReportRecord[];
